#!/usr/bin/env python3
"""
Convert the SAP Zeitkonto Excel file to SQL INSERT statements.

Usage:
    python3 tools/import_excel.py /path/to/excel.xlsx > import.sql
    psql $DATABASE_URL < import.sql

Groups multi-session rows (no date, but has start/end times) with their
parent date row into multiple time_blocks per time_entry.
"""

import sys
import uuid
from datetime import datetime, time
from decimal import Decimal

import openpyxl


def main():
    if len(sys.argv) < 2:
        print("Usage: python3 import_excel.py <path-to-excel>", file=sys.stderr)
        sys.exit(1)

    path = sys.argv[1]
    wb = openpyxl.load_workbook(path, data_only=True)
    ws = wb["Zeitkonto"]

    print("-- Generated by import_excel.py")
    print("-- Source:", path)
    print(f"-- Generated at: {datetime.now().isoformat()}")
    print()
    print("BEGIN;")
    print()

    current_entry_id = None
    current_date = None
    block_order = 0

    for row_idx, row in enumerate(ws.iter_rows(min_row=3, values_only=True), start=3):
        date_val = row[0]
        start_val = row[1]
        end_val = row[2]
        break_val = row[3]
        target_val = row[5]
        note_val = row[7]

        # Skip the SUM row and empty rows
        if date_val == "SUM":
            break
        if start_val is None and end_val is None:
            continue

        # Determine if this is a new day or a continuation
        if date_val is not None:
            if isinstance(date_val, datetime):
                current_date = date_val.date()
            else:
                continue

            current_entry_id = str(uuid.uuid4())
            block_order = 0

            target = Decimal(str(target_val)) if target_val is not None else Decimal("8.0")
            note_sql = f"'{escape_sql(str(note_val))}'" if note_val else "NULL"

            print(f"INSERT INTO time_entries (id, date, target_hours, note)")
            print(f"VALUES ('{current_entry_id}', '{current_date}', {target}, {note_sql});")
        else:
            if current_entry_id is None:
                continue
            block_order += 1

        if start_val is None:
            continue

        start_str = format_time(start_val)
        end_str = format_time(end_val) if end_val else "NULL"
        end_sql = f"'{end_str}'" if end_str != "NULL" else "NULL"

        break_hours = Decimal(str(break_val)) if break_val else Decimal("0")

        block_id = str(uuid.uuid4())
        print(f"INSERT INTO time_blocks (id, entry_id, start_time, end_time, break_hours, sort_order)")
        print(f"VALUES ('{block_id}', '{current_entry_id}', '{start_str}', {end_sql}, {break_hours}, {block_order});")

    print()
    print("COMMIT;")


def format_time(t):
    if isinstance(t, time):
        return t.strftime("%H:%M:%S")
    if isinstance(t, datetime):
        return t.strftime("%H:%M:%S")
    return str(t)


def escape_sql(s):
    return s.replace("'", "''")


if __name__ == "__main__":
    main()
