#!/usr/bin/env python3
"""
Convert the SAP Zeitkonto Excel file to SQL INSERT statements.

Usage:
    python3 tools/import_excel.py /path/to/excel.xlsx > import.sql
    psql $DATABASE_URL < import.sql

Groups multi-session rows (no date, but has start/end times) with their
parent date row into multiple time_blocks per time_entry.
Accumulates Soll (target hours) from continuation rows into the entry target.
"""

import sys
import uuid
from datetime import datetime, time, date
from decimal import Decimal

import openpyxl

# Rows with no Ist/Soll formula and no times at all - incomplete in this export,
# not a real day. Excluded entirely so they don't show up as a -Soll day in the
# saldo. Re-check against the final/newer export before the production import.
SKIP_DATES = {date(2026, 3, 18)}


def main():
    if len(sys.argv) < 2:
        print("Usage: python3 import_excel.py <path-to-excel>", file=sys.stderr)
        sys.exit(1)

    path = sys.argv[1]
    wb = openpyxl.load_workbook(path, data_only=True)
    ws = wb["Zeitkonto"]

    # Collect and merge all days: date -> (target, note, [(start, end, break)])
    days_map = {}  # date -> [target, note, blocks]
    current_date = None
    skip_current = False

    for row in ws.iter_rows(min_row=3, values_only=True):
        date_val = row[0]
        start_val = row[1]
        end_val = row[2]
        break_val = row[3]
        soll_val = row[5]
        note_val = row[7]

        if date_val == "SUM":
            break
        if date_val is not None:
            if not isinstance(date_val, datetime):
                current_date = None
                skip_current = False
                continue

            current_date = date_val.date()
            skip_current = current_date in SKIP_DATES
            if skip_current:
                continue

            soll = Decimal(str(soll_val)) if soll_val is not None else Decimal("8.0")
            if current_date not in days_map:
                days_map[current_date] = [soll, note_val, []]
            else:
                # Merge: accumulate target and note from duplicate date rows
                days_map[current_date][0] += soll
                if not days_map[current_date][1] and note_val:
                    days_map[current_date][1] = note_val
        else:
            # Continuation row
            if current_date is None or skip_current:
                continue
            if start_val is None and end_val is None and not soll_val:
                continue
            if soll_val:
                days_map[current_date][0] += Decimal(str(soll_val))

        if skip_current or start_val is None:
            continue

        start_str = format_time(start_val)
        end_str = format_time(end_val) if end_val is not None else None
        break_hours = Decimal(str(break_val)) if break_val else Decimal("0")
        days_map[current_date][2].append((start_str, end_str, break_hours))

    unique_days = [(date, data[0], data[1], data[2]) for date, data in sorted(days_map.items())]

    print("-- Generated by import_excel.py")
    print("-- Source:", path)
    print(f"-- Generated at: {datetime.now().isoformat()}")
    print()
    print("BEGIN;")
    print()

    for date, target, note, blocks in unique_days:
        entry_id = str(uuid.uuid4())
        note_sql = f"'{escape_sql(str(note))}'" if note else "NULL"

        print(f"INSERT INTO time_entries (id, date, target_hours, note)")
        print(f"VALUES ('{entry_id}', '{date}', {target}, {note_sql});")

        for sort_order, (start_str, end_str, break_hours) in enumerate(blocks):
            end_sql = f"'{end_str}'" if end_str is not None else "NULL"
            block_id = str(uuid.uuid4())
            print(f"INSERT INTO time_blocks (id, entry_id, start_time, end_time, break_hours, sort_order)")
            print(f"VALUES ('{block_id}', '{entry_id}', '{start_str}', {end_sql}, {break_hours}, {sort_order});")

    print()
    print("COMMIT;")


def format_time(t):
    if isinstance(t, time):
        return t.strftime("%H:%M:%S")
    if isinstance(t, datetime):
        return t.strftime("%H:%M:%S")
    return str(t)


def escape_sql(s):
    return s.replace("'", "''")


if __name__ == "__main__":
    main()
